### ISSUE TITLE
Avoid using getters for constants

### ISSUE THREAD

**Issue by jpeletier** [krzkaczor/TypeChain#36]
The underlying implementation of a constant function invokes the web3 RPC to obtain the value. This is more than an idempotent operation and uses network resources / may block to obtain the reply.

Using getters sends the wrong message to the developers and the debugger:

* The debugger for instance happily invokes getters when asked to explore an object which may cause problems/interfere during a debugging session.
* Developers may think that the value can be quickly accessible and thus understand they should not cache the returned value.
* In solidity, the code shows as a function, so one would expect a function to be exposed in TypeScript, not a getter.
* It is odd to await on a getter (return a Promise), since the returned value should be available instantaneously.

Happy to submit a PR to correct this.

**Comment by krzkaczor** [comment]
It was one of the decisions that I wasn't really confident of, I guess I wanted to keep things very minimal 😆 

They are typed properly (they return a promise) so it's not that bad to misuse them but I get your points. Also, I generally tend to avoid getters b/c in pure JS they can be really hard to work with.

I would love to see a PR changing it :)

**Comment by Stradivario** [comment]
As far as i know even getters inside Ethereum Chain are async methods provided by the RPC.
So when you execute get you will not pay for Gas but the server will need to look for this particular block related with contract creation.

You could do something like this

```typescript
import { GapiController, Type, Public, Query } from '@gapi/core';
import { EthereumCrowdsaleType } from './types/crowdsale-info.type';
import { PhoneumCoinCrowdsale } from '../core/ethereum/contracts/PhoneumCoinCrowdsale';

@GapiController()
export class EthereumQueriesController {

    constructor(
        private phoneumCrowdsale: PhoneumCoinCrowdsale
    ) { }

    @Type(EthereumCrowdsaleType)
    @Public()
    @Query()
    async getCrowdsaleInfo(root, payload, context): Promise<EthereumCrowdsaleType> {
        const crowdsale = await this.phoneumCrowdsale;
        return {
            startTime: (await crowdsale.startTime).toNumber(),
            endTime: (await crowdsale.endTime).toNumber(),
            hasEnded: await crowdsale.hasEnded,
            token: await crowdsale.token,
            weiRaised: (await crowdsale.weiRaised).toNumber(),
            wallet: await crowdsale.wallet,
        };
    }

}
```


Here is a implementation using @gapi graphQL framework and TypeChain:

https://github.com/Stradivario/gapi-ethereum

**Comment by jpeletier** [comment]
The problem with this is not with Ethereum per se, it is that the getter would be doing an RPC call, and its outcome, with all the I/O (HTTP request going to your RPC server and back) and may not be an idempotent operation.

**Comment by krzkaczor** [comment]
@jpeletier I am gonna close it, in `0.3` version we just generate typings for well-known libraries like truffle or web3-1.0 so it's fixed (or basically out of the scope of Typechain)
