### ISSUE TITLE
remove unused imports with generated contracts

### ISSUE THREAD

**Issue by Stradivario** [krzkaczor/TypeChain#48]
Result:
tsconfig with noUnusedLocals is not compiling because of IPayableTxParams and ITxParams are not used sometimes but they present inside the compiled source.

Expected: 
ITxParams and IPayableTxParams to not present inside build

Really good work !! Thank you for this repository :)

Regards,
Kristiyan Tachev

**Comment by desfero** [comment]
@krzkaczor @Stradivario I'm working on a fix

**Comment by Stradivario** [comment]
@desfero thank you man!!! You are more than welcome introducing this "shiet" :D

**Comment by krzkaczor** [comment]
Released in `typechain@0.2.5`. Thanks for help!
