### ISSUE TITLE
compilation error in typechain-runtime with noUnusedParameters

### ISSUE THREAD

**Issue by quezak** [krzkaczor/TypeChain#78]
with `noUnusedParameters` compiler option enabled, I get the following error:
```
$ rm -rf dist && npx tsc -p .
build/ts_contracts/typechain-runtime.ts:98:42 - error TS6133: 'res2' is declared but its value is never read.

98         watchedEvent.stopWatching((err2, res2) => {
                                            ~~~~
```

Could you please rename the unused param to `_res2` (or remove it)?  I'd submit a PR, but the change is really small, so let's not waste time for bureaucracy :)

**Comment by krzkaczor** [comment]
If its unused, it should be removed. I will make sure to tweak compiler settings to cath these mistakes in future. Sorry about that.

**Comment by quezak** [comment]
Thanks!
